source 'https://rubygems.org'
ruby '2.4.1'

gem 'annotate'
gem 'factory_bot_rails'
gem 'figaro'
gem 'htmlentities'
gem 'jquery-rails'
gem 'levenshtein'
gem 'nokogiri'
gem 'pg'
gem 'rails'
gem 'rb-readline'
gem 'rspec-rails'
gem 'turbolinks'
gem 'twitter'
gem 'uglifier'
