development:
  adapter: postgresql
  encoding: unicode
  database: jeopardy-bot_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: jeopardy-bot_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: jeopardy-bot_production
  pool: 5
  username:
  password:
